<?php

namespace WhatsAppAutomation;

class APIClient {
    private $api_base;
    private $timeout;

    public function __construct() {
        $stored_base = trim((string) get_option('whatsapp_automation_api_base_url', ''));
        $legacy_default = rtrim((string) WHATSAPP_AUTOMATION_DEFAULT_API_BASE, '/');
        $smart_default = rtrim($this->get_smart_default_api_base(), '/');

        // Auto-heal legacy localhost default on live sites to prevent 404 errors.
        if ($stored_base === '') {
            $this->api_base = $smart_default;
            update_option('whatsapp_automation_api_base_url', $this->api_base);
        } else {
            $normalized = rtrim($this->normalize_known_hosts_base($stored_base), '/');
            if ($normalized === $legacy_default && $smart_default !== $legacy_default) {
                $normalized = $smart_default;
                update_option('whatsapp_automation_api_base_url', $normalized);
            } elseif ($normalized !== rtrim($stored_base, '/')) {
                update_option('whatsapp_automation_api_base_url', $normalized);
            }
            $this->api_base = $normalized;
        }

        $this->timeout = 30;
    }

    public function get_api_base() {
        return $this->api_base;
    }

    public function is_authenticated() {
        $api_key = (string) get_option('whatsapp_automation_api_key', '');
        if ($api_key !== '') {
            return true;
        }

        $access_token = (string) get_option('whatsapp_automation_access_token', '');
        $refresh_token = (string) get_option('whatsapp_automation_refresh_token', '');
        return ($access_token !== '' && $refresh_token !== '');
    }

    public function get_masked_api_key() {
        $api_key = (string) get_option('whatsapp_automation_api_key', '');
        if ($api_key === '') {
            return '';
        }

        if (strlen($api_key) <= 14) {
            return $api_key;
        }

        return substr($api_key, 0, 10) . '...' . substr($api_key, -4);
    }

    public function save_api_key($api_key) {
        $api_key = sanitize_text_field((string) $api_key);
        if ($api_key === '') {
            delete_option('whatsapp_automation_api_key');
            return true;
        }

        if (strpos($api_key, 'sk_live_') !== 0 && strpos($api_key, 'sk_test_') !== 0) {
            return new \WP_Error('wa_invalid_api_key', __('Invalid API key format.', 'wapid-automation-for-woocommerce'));
        }

        $previous = (string) get_option('whatsapp_automation_api_key', '');
        update_option('whatsapp_automation_api_key', $api_key);

        // Validate key immediately against an API-key compatible endpoint.
        $check = $this->get_instances();
        if (is_wp_error($check)) {
            if ($previous !== '') {
                update_option('whatsapp_automation_api_key', $previous);
            } else {
                delete_option('whatsapp_automation_api_key');
            }
            return $check;
        }

        return true;
    }

    public function generate_wordpress_api_key() {
        $access_token = (string) get_option('whatsapp_automation_access_token', '');
        if ($access_token === '') {
            return new \WP_Error('wa_missing_token', __('JWT access token not available. Please connect first or add API key manually.', 'wapid-automation-for-woocommerce'));
        }

        $site_host = wp_parse_url(site_url('/'), PHP_URL_HOST);
        $name = 'WordPress ' . ($site_host ? strtoupper((string) $site_host) : 'Site');
        $description = 'Auto-generated by Wapid WordPress plugin for ' . site_url('/');

        $payload = array(
            'name' => $name,
            'source' => 'wordpress',
            'description' => $description,
            'environment' => 'live',
            'permissions' => array('read', 'write'),
            'rate_limit' => 1000,
        );

        $url = $this->api_base . '/api-keys';
        $response = wp_remote_request($url, array(
            'method' => 'POST',
            'timeout' => $this->timeout,
            'headers' => array(
                'Content-Type' => 'application/json',
                'User-Agent' => 'Wapid-WP/' . WHATSAPP_AUTOMATION_VERSION,
                'Authorization' => 'Bearer ' . $access_token,
            ),
            'body' => wp_json_encode($payload),
        ));

        if (is_wp_error($response)) {
            return $response;
        }

        $status = (int) wp_remote_retrieve_response_code($response);
        $decoded = json_decode(wp_remote_retrieve_body($response), true);
        if (!is_array($decoded)) {
            $decoded = array();
        }

        if ($status >= 400) {
            $message = $decoded['error']['message'] ?? $decoded['message'] ?? ('API Error: ' . $status);
            return new \WP_Error('wa_api_error', $message, array('status' => $status, 'body' => $decoded));
        }

        $api_key = (string) ($decoded['data']['apiKey'] ?? $decoded['apiKey'] ?? '');
        if ($api_key === '') {
            return new \WP_Error('wa_api_key_missing', __('API key generation succeeded but key was not returned.', 'wapid-automation-for-woocommerce'));
        }

        $save = $this->save_api_key($api_key);
        if (is_wp_error($save)) {
            return $save;
        }

        return array(
            'apiKey' => $api_key,
            'masked' => $this->get_masked_api_key(),
        );
    }

    public function login($email, $password) {
        $response = $this->request('POST', '/auth/login', array(
            'email' => sanitize_email($email),
            'password' => (string) $password,
        ), false);

        if (is_wp_error($response)) {
            return $response;
        }

        $this->store_tokens($response);
        return $response;
    }

    public function register($payload) {
        $response = $this->request('POST', '/auth/register', $payload, false);
        if (is_wp_error($response)) {
            return $response;
        }

        $this->store_tokens($response);
        return $response;
    }

    public function logout() {
        delete_option('whatsapp_automation_api_key');
        delete_option('whatsapp_automation_access_token');
        delete_option('whatsapp_automation_refresh_token');
        delete_option('whatsapp_automation_token_expires_at');
    }

    public function refresh_token() {
        $refresh_token = get_option('whatsapp_automation_refresh_token', '');
        if (empty($refresh_token)) {
            return new \WP_Error('wa_missing_refresh', __('Refresh token not found.', 'wapid-automation-for-woocommerce'));
        }

        $response = $this->request('POST', '/auth/refresh', array('refresh_token' => $refresh_token), false);
        if (is_wp_error($response)) {
            $message = strtolower((string) $response->get_error_message());
            if (strpos($message, 'invalid refresh token') !== false || strpos($message, 'jwt') !== false) {
                // Keep local auth state in sync when backend refresh token is rejected.
                $this->logout();
            }
            return $response;
        }

        if (!empty($response['access_token'])) {
            update_option('whatsapp_automation_access_token', sanitize_text_field($response['access_token']));
            if (!empty($response['expires_in'])) {
                update_option('whatsapp_automation_token_expires_at', time() + (int) $response['expires_in']);
            }
        }
        if (!empty($response['refresh_token'])) {
            update_option('whatsapp_automation_refresh_token', sanitize_text_field($response['refresh_token']));
        }

        return $response;
    }

    public function get_me() {
        return $this->request('GET', '/auth/me');
    }

    public function get_dashboard_stats() {
        return $this->request('GET', '/dashboard/stats');
    }

    public function get_instances() {
        return $this->request('GET', '/instances');
    }

    public function get_instance_status($instance_id) {
        return $this->request('GET', '/instances/' . rawurlencode($instance_id) . '/status');
    }

    public function get_instance_qr($instance_id) {
        return $this->request('GET', '/instances/' . rawurlencode($instance_id) . '/qr');
    }

    public function start_instance($instance_id) {
        return $this->request('POST', '/instances/' . rawurlencode($instance_id) . '/start', array());
    }

    public function stop_instance($instance_id) {
        return $this->request('POST', '/instances/' . rawurlencode($instance_id) . '/stop', array());
    }

    public function restart_instance($instance_id) {
        return $this->request('POST', '/instances/' . rawurlencode($instance_id) . '/restart', array());
    }

    public function logout_instance($instance_id) {
        return $this->request('POST', '/instances/' . rawurlencode($instance_id) . '/logout', array());
    }

    public function get_templates() {
        return $this->request('GET', '/templates');
    }

    public function create_template($name, $category, $content) {
        return $this->request('POST', '/templates', array(
            'name' => sanitize_text_field($name),
            'category' => sanitize_text_field($category),
            'content' => wp_kses_post($content),
        ));
    }

    public function delete_template($template_id) {
        return $this->request('DELETE', '/templates/' . rawurlencode($template_id));
    }

    public function get_messages($instance_id = '', $limit = 20, $offset = 0) {
        $query = array(
            'limit' => (int) $limit,
            'offset' => (int) $offset,
        );
        if ($instance_id !== '') {
            $query['instanceId'] = $instance_id;
        }
        return $this->request('GET', '/messages?' . http_build_query($query));
    }

    public function send_message($instance_id, $recipient_phone, $message_text) {
        return $this->request('POST', '/messages/send', array(
            'instance_id' => $instance_id,
            'recipient_phone' => preg_replace('/\D+/', '', $recipient_phone),
            'message_text' => $message_text,
        ));
    }

    /**
     * Resolve a sendable instance ID for WordPress flows.
     * Priority:
     * 1) Preferred instance if connected (+ running when running_status is present)
     * 2) Any connected + running instance
     * 3) Any connected instance
     */
    public function resolve_sendable_instance_id($preferred_instance_id = '') {
        $preferred_instance_id = sanitize_text_field((string) $preferred_instance_id);
        $instances_response = $this->get_instances();

        if (is_wp_error($instances_response)) {
            return $instances_response;
        }

        $instances = $this->extract_items($instances_response);
        if (empty($instances)) {
            return new \WP_Error('wa_no_instances', __('No instances found in your account.', 'wapid-automation-for-woocommerce'));
        }

        $preferred = null;
        foreach ($instances as $instance) {
            if (($instance['id'] ?? '') === $preferred_instance_id) {
                $preferred = $instance;
                break;
            }
        }

        if ($preferred && $this->is_sendable_instance($preferred)) {
            return $preferred_instance_id;
        }

        foreach ($instances as $instance) {
            if ($this->is_sendable_instance($instance)) {
                return (string) ($instance['id'] ?? '');
            }
        }

        foreach ($instances as $instance) {
            if (($instance['status'] ?? '') === 'connected') {
                return (string) ($instance['id'] ?? '');
            }
        }

        $status = $preferred ? (string) ($preferred['status'] ?? 'unknown') : 'unknown';
        return new \WP_Error(
            'wa_no_connected_instance',
            sprintf(__('No connected instance available. Selected instance status: %s', 'wapid-automation-for-woocommerce'), $status)
        );
    }

    /**
     * Normalize API collections where different backend versions may return:
     * - ['data' => [ ... ]]
     * - ['data' => ['items' => [ ... ]]]
     * - ['items' => [ ... ]]
     * - [ ... ]
     */
    public function extract_items($response) {
        if (!is_array($response)) {
            return array();
        }

        if (isset($response['data']) && is_array($response['data']) && $this->is_list_array($response['data'])) {
            return $response['data'];
        }

        if (isset($response['data']['items']) && is_array($response['data']['items'])) {
            return $response['data']['items'];
        }

        if (isset($response['items']) && is_array($response['items'])) {
            return $response['items'];
        }

        if ($this->is_list_array($response)) {
            return $response;
        }

        return array();
    }

    /**
     * Normalize single payload where backend may return nested data.
     */
    public function extract_payload($response) {
        if (!is_array($response)) {
            return array();
        }

        if (isset($response['data']) && is_array($response['data'])) {
            return $response['data'];
        }

        return $response;
    }

    private function is_list_array($value) {
        if (!is_array($value)) {
            return false;
        }

        if (function_exists('array_is_list')) {
            return array_is_list($value);
        }

        return array_keys($value) === range(0, count($value) - 1);
    }

    private function is_sendable_instance($instance) {
        if (!is_array($instance)) {
            return false;
        }

        if (($instance['status'] ?? '') !== 'connected') {
            return false;
        }

        $running_status = (string) ($instance['running_status'] ?? '');
        if ($running_status !== '' && $running_status !== 'running') {
            return false;
        }

        return !empty($instance['id']);
    }

    private function get_smart_default_api_base() {
        $site_host = wp_parse_url(site_url('/'), PHP_URL_HOST);
        $is_local = $site_host && (
            stripos($site_host, 'localhost') !== false ||
            stripos($site_host, '.local') !== false ||
            stripos($site_host, '127.0.0.1') !== false
        );

        if ($is_local) {
            return WHATSAPP_AUTOMATION_DEFAULT_API_BASE;
        }

        return 'https://api.wapid.net/api/v1';
    }

    private function normalize_known_hosts_base($base) {
        $base = trim((string) $base);
        $parsed = wp_parse_url($base);
        if (!is_array($parsed)) {
            return $base;
        }

        $host = strtolower((string) ($parsed['host'] ?? ''));
        $scheme = (string) ($parsed['scheme'] ?? 'https');
        $path = '/' . ltrim((string) ($parsed['path'] ?? ''), '/');
        $path = rtrim($path, '/');
        if ($path === '') {
            $path = '/';
        }

        if (strpos($host, 'api.wapid.net') !== false && ($path === '/' || $path === '/api')) {
            $port = isset($parsed['port']) ? ':' . (int) $parsed['port'] : '';
            return $scheme . '://' . $host . $port . '/api/v1';
        }

        if ($host === 'wapid.net' && ($path === '/' || $path === '/api')) {
            $port = isset($parsed['port']) ? ':' . (int) $parsed['port'] : '';
            return $scheme . '://' . $host . $port . '/api/v1';
        }

        return $base;
    }

    private function ensure_access_token() {
        $api_key = (string) get_option('whatsapp_automation_api_key', '');
        if ($api_key !== '') {
            return true;
        }

        $expires_at = (int) get_option('whatsapp_automation_token_expires_at', 0);
        $access_token = get_option('whatsapp_automation_access_token', '');

        if (empty($access_token)) {
            return new \WP_Error('wa_missing_token', __('Please login first.', 'wapid-automation-for-woocommerce'));
        }

        if ($expires_at > 0 && ($expires_at - 60) <= time()) {
            $refresh = $this->refresh_token();
            if (is_wp_error($refresh)) {
                return $refresh;
            }
        }

        return true;
    }

    private function request($method, $endpoint, $data = null, $auth_required = true, $retry = true) {
        if ($auth_required) {
            $token_check = $this->ensure_access_token();
            if (is_wp_error($token_check)) {
                return $token_check;
            }
        }

        $url = $this->api_base . $endpoint;
        $headers = array(
            'Content-Type' => 'application/json',
            'User-Agent' => 'Wapid-WP/' . WHATSAPP_AUTOMATION_VERSION,
        );

        if ($auth_required) {
            $api_key = (string) get_option('whatsapp_automation_api_key', '');
            if ($api_key !== '') {
                $headers['Authorization'] = 'Bearer ' . $api_key;
                $headers['X-Wapid-Source'] = 'wordpress';
            } else {
                $headers['Authorization'] = 'Bearer ' . get_option('whatsapp_automation_access_token', '');
            }
        }

        $args = array(
            'method' => $method,
            'timeout' => $this->timeout,
            'headers' => $headers,
        );

        if ($data !== null) {
            $args['body'] = wp_json_encode($data);
        }

        $response = wp_remote_request($url, $args);
        if (is_wp_error($response)) {
            return $response;
        }

        $status = (int) wp_remote_retrieve_response_code($response);
        $body = wp_remote_retrieve_body($response);
        $decoded = json_decode($body, true);
        if (!is_array($decoded)) {
            $decoded = array();
        }

        $api_key_current = (string) get_option('whatsapp_automation_api_key', '');
        $api_key_mode = ($api_key_current !== '');
        if ($status === 401 && $auth_required && $retry) {
            if ($api_key_mode) {
                $has_tokens = ((string) get_option('whatsapp_automation_access_token', '') !== '' && (string) get_option('whatsapp_automation_refresh_token', '') !== '');
                if ($has_tokens) {
                    // Backward compatibility: if API key is invalid/revoked, try legacy token flow.
                    delete_option('whatsapp_automation_api_key');
                    $fallback = $this->request($method, $endpoint, $data, $auth_required, false);
                    update_option('whatsapp_automation_api_key', $api_key_current);
                    if (!is_wp_error($fallback)) {
                        return $fallback;
                    }
                }
            } else {
                $refresh = $this->refresh_token();
                if (!is_wp_error($refresh)) {
                    return $this->request($method, $endpoint, $data, $auth_required, false);
                }
            }
        }

        if ($status >= 400) {
            $message = $decoded['error']['message'] ?? $decoded['message'] ?? ('API Error: ' . $status);
            return new \WP_Error('wa_api_error', $message, array('status' => $status, 'body' => $decoded));
        }

        return $decoded;
    }

    private function store_tokens($response) {
        if (!empty($response['access_token'])) {
            update_option('whatsapp_automation_access_token', sanitize_text_field($response['access_token']));
        }

        if (!empty($response['refresh_token'])) {
            update_option('whatsapp_automation_refresh_token', sanitize_text_field($response['refresh_token']));
        }

        if (!empty($response['expires_in'])) {
            update_option('whatsapp_automation_token_expires_at', time() + (int) $response['expires_in']);
        }
    }
}
